import { createFileRoute } from '@tanstack/react-router';
import { ContactButtons } from '@/components/site-sections';
import { locations } from '@/lib/site-data';
const place = locations[0];
export const Route = createFileRoute('/sedi/san-donato-milanese')({ head: () => ({ meta: [
  { title: 'Osteopata a San Donato Milanese | Angelo Barone' }, { name: 'description', content: 'Ricevo a San Donato Milanese in Via Enrico Mattei 54, vicino MM3. Scopri orari, tariffa e come contattarmi.' },
  { property: 'og:title', content: 'Osteopata a San Donato Milanese | Angelo Barone' }, { property: 'og:description', content: 'Via Enrico Mattei 54, vicino MM3. Seduta 65 €. Scrivimi per prenotare.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' },
] }), component: SanDonato });
function SanDonato() { return <main><section className="section-space bg-linen"><div className="site-container grid lg:grid-cols-[1.2fr_.8fr] gap-12 lg:gap-24"><div><p className="text-sm mb-5">Dove ricevo · Sede principale</p><h1 className="display-heading text-[clamp(68px,8vw,120px)]">San Donato<br/><em>Milanese.</em></h1><p className="body-large mt-8 max-w-[620px]">Mi trovi in Via Enrico Mattei 54, vicino alla MM3. Qui ho più disponibilità durante la settimana: scrivimi e troviamo un momento comodo per te.</p><div className="mt-10"><ContactButtons /></div></div><div className="bg-primary text-primary-foreground rounded-xl p-8 md:p-10 self-start"><h2 className="font-display text-5xl mb-8">Informazioni pratiche</h2><div className="border-t border-light-green/40 py-5"><p className="text-light-green text-sm mb-2">Indirizzo</p><p className="text-lg">{place.address}</p><p className="text-sm mt-1">{place.note}</p></div><div className="border-t border-light-green/40 py-5"><p className="text-light-green text-sm mb-2">Orari</p>{place.hours.map(hour => <p key={hour} className="leading-8">{hour}</p>)}</div><div className="border-t border-light-green/40 pt-5"><p className="text-light-green text-sm mb-2">Tariffa</p><p className="text-2xl">{place.price}</p></div></div></div></section></main>; }
