import { Link } from '@tanstack/react-router';
import { Button } from '@/components/ui/button';
import { MessageCircle, Phone, MapPin } from 'lucide-react';
import { whatsapp, locations } from '@/lib/site-data';

export function ContactButtons({ light = false }: { light?: boolean }) {
  return <div className="flex flex-wrap gap-3"><Button asChild size="lg" variant={light ? 'secondary' : 'default'} className="h-12 px-6 text-[15px]"><a href={whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle /> Scrivimi su WhatsApp</a></Button><Button asChild size="lg" variant="outline" className="h-12 px-6 text-[15px]"><a href="tel:+393288778394"><Phone /> Chiamami</a></Button></div>;
}
export function BookingSection() {
  return <section id="prenota" className="bg-primary text-primary-foreground section-space"><div className="site-container grid gap-10 lg:grid-cols-[.85fr_1fr] lg:gap-20"><div><p className="text-light-green text-sm mb-5">Prenota una visita</p><h2 className="display-heading text-[clamp(56px,6.5vw,96px)]">Parliamone<br /><em>direttamente.</em></h2></div><div className="lg:pt-12"><p className="body-large max-w-[610px]">Per prenotare scrivimi su WhatsApp o chiamami — ti rispondo io, personalmente. Ci sentiamo, capiamo insieme di cosa hai bisogno e troviamo data e sede più comode. Per disdire, avvisami almeno 24 ore prima.</p><div className="mt-9"><ContactButtons light /></div></div></div></section>;
}
export function LocationSummary() {
  return <section id="sedi" className="section-space"><div className="site-container"><div className="flex flex-wrap justify-between items-end gap-8 mb-12"><div><p className="text-sm mb-4">Dove ricevo</p><h2 className="display-heading text-[clamp(56px,6vw,90px)]">Troviamoci vicino a te.</h2></div><p className="max-w-[320px] text-muted-foreground leading-relaxed">Ricevo in tre sedi. A San Donato Milanese ho più disponibilità durante la settimana.</p></div><div className="grid lg:grid-cols-[1.3fr_.7fr] gap-4"><article className="bg-primary text-primary-foreground rounded-xl p-8 md:p-12 lg:row-span-2 min-h-[470px] flex flex-col justify-between"><div><div className="flex items-center gap-2 text-light-green text-sm mb-8"><MapPin size={16}/> Sede principale · Vicino MM3</div><h3 className="display-heading text-[clamp(50px,5vw,76px)] max-w-[500px]">San Donato<br />Milanese</h3><p className="text-xl mt-4">Via Enrico Mattei 54</p></div><div><div className="border-t border-light-green/40 pt-6 mt-8 flex flex-col sm:flex-row justify-between gap-8"><div><p className="text-sm text-light-green mb-3">Quando ricevo</p><p className="leading-8">Lun/Mar 8:00–20:00<br/>Mer 8:00–13:00<br/>Sab 8:00–12:30</p></div><div><p className="text-sm text-light-green mb-3">Seduta</p><p className="text-2xl">65 €</p></div></div><Button asChild variant="secondary" className="mt-8"><Link to="/sedi/san-donato-milanese">Scopri la sede</Link></Button></div></article><div className="grid gap-4">{locations.slice(1).map(location => <article key={location.name} className="bg-linen rounded-xl p-7 md:p-9 flex flex-col justify-between min-h-[220px]"><div><h3 className="font-display text-4xl md:text-5xl">{location.name}</h3><p className="mt-2 text-sm leading-relaxed">{location.address}</p><p className="text-sm text-muted-foreground mt-1">{location.note}</p></div><div className="flex items-end justify-between gap-4 mt-5"><span className="text-sm font-medium">{location.price}</span><Link className="text-link text-sm shrink-0" to={location.slug}>La sede</Link></div></article>)}</div></div></div></section>;
}
