/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CervicaleRouteImport } from './routes/cervicale'
import { Route as ChiSonoRouteImport } from './routes/chi-sono'
import { Route as GravidanzaRouteImport } from './routes/gravidanza'
import { Route as MalDiSchienaRouteImport } from './routes/mal-di-schiena'
import { Route as OsteopatiaSportivaRouteImport } from './routes/osteopatia-sportiva'
import { Route as PavimentoPelvicoRouteImport } from './routes/pavimento-pelvico'
import { Route as SediCantuRouteImport } from './routes/sedi/cantu'
import { Route as SediGiussanoRouteImport } from './routes/sedi/giussano'
import { Route as SediSanDonatoMilaneseRouteImport } from './routes/sedi/san-donato-milanese'
import { Route as TrattamentiSlugRouteImport } from './routes/trattamenti.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CervicaleRoute = CervicaleRouteImport.update({
  id: '/cervicale',
  path: '/cervicale',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSonoRoute = ChiSonoRouteImport.update({
  id: '/chi-sono',
  path: '/chi-sono',
  getParentRoute: () => rootRouteImport,
} as any)
const GravidanzaRoute = GravidanzaRouteImport.update({
  id: '/gravidanza',
  path: '/gravidanza',
  getParentRoute: () => rootRouteImport,
} as any)
const MalDiSchienaRoute = MalDiSchienaRouteImport.update({
  id: '/mal-di-schiena',
  path: '/mal-di-schiena',
  getParentRoute: () => rootRouteImport,
} as any)
const OsteopatiaSportivaRoute = OsteopatiaSportivaRouteImport.update({
  id: '/osteopatia-sportiva',
  path: '/osteopatia-sportiva',
  getParentRoute: () => rootRouteImport,
} as any)
const PavimentoPelvicoRoute = PavimentoPelvicoRouteImport.update({
  id: '/pavimento-pelvico',
  path: '/pavimento-pelvico',
  getParentRoute: () => rootRouteImport,
} as any)
const SediCantuRoute = SediCantuRouteImport.update({
  id: '/sedi/cantu',
  path: '/sedi/cantu',
  getParentRoute: () => rootRouteImport,
} as any)
const SediGiussanoRoute = SediGiussanoRouteImport.update({
  id: '/sedi/giussano',
  path: '/sedi/giussano',
  getParentRoute: () => rootRouteImport,
} as any)
const SediSanDonatoMilaneseRoute = SediSanDonatoMilaneseRouteImport.update({
  id: '/sedi/san-donato-milanese',
  path: '/sedi/san-donato-milanese',
  getParentRoute: () => rootRouteImport,
} as any)
const TrattamentiSlugRoute = TrattamentiSlugRouteImport.update({
  id: '/trattamenti/$slug',
  path: '/trattamenti/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cervicale': typeof CervicaleRoute
  '/chi-sono': typeof ChiSonoRoute
  '/gravidanza': typeof GravidanzaRoute
  '/mal-di-schiena': typeof MalDiSchienaRoute
  '/osteopatia-sportiva': typeof OsteopatiaSportivaRoute
  '/pavimento-pelvico': typeof PavimentoPelvicoRoute
  '/sedi/cantu': typeof SediCantuRoute
  '/sedi/giussano': typeof SediGiussanoRoute
  '/sedi/san-donato-milanese': typeof SediSanDonatoMilaneseRoute
  '/trattamenti/$slug': typeof TrattamentiSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cervicale': typeof CervicaleRoute
  '/chi-sono': typeof ChiSonoRoute
  '/gravidanza': typeof GravidanzaRoute
  '/mal-di-schiena': typeof MalDiSchienaRoute
  '/osteopatia-sportiva': typeof OsteopatiaSportivaRoute
  '/pavimento-pelvico': typeof PavimentoPelvicoRoute
  '/sedi/cantu': typeof SediCantuRoute
  '/sedi/giussano': typeof SediGiussanoRoute
  '/sedi/san-donato-milanese': typeof SediSanDonatoMilaneseRoute
  '/trattamenti/$slug': typeof TrattamentiSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cervicale': typeof CervicaleRoute
  '/chi-sono': typeof ChiSonoRoute
  '/gravidanza': typeof GravidanzaRoute
  '/mal-di-schiena': typeof MalDiSchienaRoute
  '/osteopatia-sportiva': typeof OsteopatiaSportivaRoute
  '/pavimento-pelvico': typeof PavimentoPelvicoRoute
  '/sedi/cantu': typeof SediCantuRoute
  '/sedi/giussano': typeof SediGiussanoRoute
  '/sedi/san-donato-milanese': typeof SediSanDonatoMilaneseRoute
  '/trattamenti/$slug': typeof TrattamentiSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cervicale'
    | '/chi-sono'
    | '/gravidanza'
    | '/mal-di-schiena'
    | '/osteopatia-sportiva'
    | '/pavimento-pelvico'
    | '/sedi/cantu'
    | '/sedi/giussano'
    | '/sedi/san-donato-milanese'
    | '/trattamenti/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cervicale'
    | '/chi-sono'
    | '/gravidanza'
    | '/mal-di-schiena'
    | '/osteopatia-sportiva'
    | '/pavimento-pelvico'
    | '/sedi/cantu'
    | '/sedi/giussano'
    | '/sedi/san-donato-milanese'
    | '/trattamenti/$slug'
  id:
    | '__root__'
    | '/'
    | '/cervicale'
    | '/chi-sono'
    | '/gravidanza'
    | '/mal-di-schiena'
    | '/osteopatia-sportiva'
    | '/pavimento-pelvico'
    | '/sedi/cantu'
    | '/sedi/giussano'
    | '/sedi/san-donato-milanese'
    | '/trattamenti/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CervicaleRoute: typeof CervicaleRoute
  ChiSonoRoute: typeof ChiSonoRoute
  GravidanzaRoute: typeof GravidanzaRoute
  MalDiSchienaRoute: typeof MalDiSchienaRoute
  OsteopatiaSportivaRoute: typeof OsteopatiaSportivaRoute
  PavimentoPelvicoRoute: typeof PavimentoPelvicoRoute
  SediCantuRoute: typeof SediCantuRoute
  SediGiussanoRoute: typeof SediGiussanoRoute
  SediSanDonatoMilaneseRoute: typeof SediSanDonatoMilaneseRoute
  TrattamentiSlugRoute: typeof TrattamentiSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cervicale': {
      id: '/cervicale'
      path: '/cervicale'
      fullPath: '/cervicale'
      preLoaderRoute: typeof CervicaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-sono': {
      id: '/chi-sono'
      path: '/chi-sono'
      fullPath: '/chi-sono'
      preLoaderRoute: typeof ChiSonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gravidanza': {
      id: '/gravidanza'
      path: '/gravidanza'
      fullPath: '/gravidanza'
      preLoaderRoute: typeof GravidanzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mal-di-schiena': {
      id: '/mal-di-schiena'
      path: '/mal-di-schiena'
      fullPath: '/mal-di-schiena'
      preLoaderRoute: typeof MalDiSchienaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osteopatia-sportiva': {
      id: '/osteopatia-sportiva'
      path: '/osteopatia-sportiva'
      fullPath: '/osteopatia-sportiva'
      preLoaderRoute: typeof OsteopatiaSportivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pavimento-pelvico': {
      id: '/pavimento-pelvico'
      path: '/pavimento-pelvico'
      fullPath: '/pavimento-pelvico'
      preLoaderRoute: typeof PavimentoPelvicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sedi/cantu': {
      id: '/sedi/cantu'
      path: '/sedi/cantu'
      fullPath: '/sedi/cantu'
      preLoaderRoute: typeof SediCantuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sedi/giussano': {
      id: '/sedi/giussano'
      path: '/sedi/giussano'
      fullPath: '/sedi/giussano'
      preLoaderRoute: typeof SediGiussanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sedi/san-donato-milanese': {
      id: '/sedi/san-donato-milanese'
      path: '/sedi/san-donato-milanese'
      fullPath: '/sedi/san-donato-milanese'
      preLoaderRoute: typeof SediSanDonatoMilaneseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trattamenti/$slug': {
      id: '/trattamenti/$slug'
      path: '/trattamenti/$slug'
      fullPath: '/trattamenti/$slug'
      preLoaderRoute: typeof TrattamentiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CervicaleRoute: CervicaleRoute,
  ChiSonoRoute: ChiSonoRoute,
  GravidanzaRoute: GravidanzaRoute,
  MalDiSchienaRoute: MalDiSchienaRoute,
  OsteopatiaSportivaRoute: OsteopatiaSportivaRoute,
  PavimentoPelvicoRoute: PavimentoPelvicoRoute,
  SediCantuRoute: SediCantuRoute,
  SediGiussanoRoute: SediGiussanoRoute,
  SediSanDonatoMilaneseRoute: SediSanDonatoMilaneseRoute,
  TrattamentiSlugRoute: TrattamentiSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
